[profile.default]
src = "contracts"
out = "out"
test = "tests/integration"
libs = ["lib", ".venv/lib/python3.12/site-packages"]

[vyper]
# TODO replace with env so that it's not hardcoded
path = "/Users/albe/.pyenv/shims/vyper"



